frontend/controllers/VoterController.php
<?php
/**
 * Created by PhpStorm.
 * User: MarchelHutagalung
 * Date: 3/22/2019
 * Time: 2:10 PM
 */

namespace frontend\controllers;


use frontend\models\search\CandidateSearch;
use frontend\models\search\VoteSearch;
use frontend\models\Token;
use frontend\models\User;
use frontend\models\Vote;
use Yii;
use yii\web\Controller;

class VoterController extends Controller
{
    public function actionIndex(){
        $searchModel = new VoteSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index',[
            'dataProvider'=>$dataProvider
        ]);
    }

    public function actionGetVote($id){
        $cek = Vote::find()->where(['vote_id'=>$id])->one();
        if(is_object($cek)){
            $time =date("Y-m-d H:i:s");
            $today = date('Y-m-d H:i:s',strtotime('+7 hour',strtotime($time)));
            $start = Yii::$app->formatter->asDatetime($cek->start_date,'php:Y-m-d H:i:s');
            $end = Yii::$app->formatter->asDatetime($cek->end_date,'php:Y-m-d H:i:s');
            if($today<$start){
                return $this->render('wait',['message'=>'Voting Belum dimulai']);
            }
            else if($today >= $start && $today <= $end){
                $vote_address = $cek->bitcoin_address;
                $searchModel = new CandidateSearch();
                $dataProvider = $searchModel->searchById(Yii::$app->request->queryParams,$id);
                $model = new Token();
                if($model->load(Yii::$app->request->post()) && $model->validate()) {
                    $status = Token::find()->where(['token' => $model->token])->one();

                    if(is_object($status)){
                        $tokenId = $status->token;
                        if ($status->is_used != 0 || $status->is_paid == 0) {
                            Yii::$app->session->setFlash('error', 'Maaf, Token anda telah digunakan atau belum diizinkan untuk voting');
                            return $this->render('insert',[
                                'model'=>$model,
                            ]);
                        } else {
                            return $this->render('ballot', [
                                'dataProvider' => $dataProvider,
                                'tokenId' => $tokenId,
                                'vote_address'=>$vote_address,
                            ]);
                        }
                    }
                    else{
                        Yii::$app->session->setFlash('error', 'Maaf, Token anda tidak valid.');
                        return $this->render('insert',[
                            'model'=>$model,
                        ]);
                    }
                }
                else{
                    return $this->render('insert',[
                        'model'=>$model,
                    ]);
                }
            }
            else{
                return $this->render('wait',['message'=>'Voting Telah Selesai']);
            }

        }
        else{
            return $this->redirect('error');
        }
    }

    public function actionResult($id){
        $model = Vote::find()->where(['vote_id'=>$id])->one();
        if(is_object($model)){
        return $this->render('result',
            [
                'model' => $model,
            ]);
        }
        else{
            return $this->redirect(['site/error']);
        }
    }

    public function actionError(){
        return $this->render('error');
    }
}

frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<style>
    body{
        font-family: Verdana;
    }
    div#LoadingImage{
        margin: auto;
        position: absolute;
        z-index: 1000;
        background-color:white;
        opacity:0.5;
        height: 100%;
    }
    #LoadingImage img{
        opacity: 1;
        width: 40%;
        padding-top: 10%;
    }
</style>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => "CHAINVOTING",
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'DAFTAR VOTING', 'url' => ['/voter/index']],
    ];
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>

        <div id="LoadingImage" class="container" style="display: none">
            <center>
                <?=Html::img('@web/images/spinner.gif')?>
            </center>
        </div>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <center>
            <strong>Copyright &copy; 2018-2019 <a href="#">TA-D3TI-04</a>.</strong> All rights
            reserved.
        </center>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>