backend/models/Vote.php
<?php

namespace backend\models;

use common\behaviors\BlameableBehavior;
use common\behaviors\DeleteBehavior;
use common\behaviors\TimestampBehavior;
use Yii;

/**
 * This is the model class for table "vote".
 *
 * @property string $vote_id
 * @property string $vote_title
 * @property string $vote_desc
 * @property int $vote_numbers
 * @property string $start_date
 * @property string $end_date
 * @property string $bitcoin_address
 * @property int $deleted
 * @property string $deleted_at
 * @property string $deleted_by
 * @property string $created_at
 * @property string $created_by
 * @property string $updated_at
 * @property string $updated_by
 *
 * @property Candidate[] $candidates
 * @property Token[] $tokens
 */
class Vote extends \yii\db\ActiveRecord
{
    /**
     * behaviour to add created_at and updatet_at field with current datetime (timestamp)
     * and created_by and updated_by field with current user id (blameable)
     */
    public function behaviors(){
        return [
            'timestamp' => [
                'class' => TimestampBehavior::className(),
            ],
            'blameable' => [
                'class' => BlameableBehavior::className(),
            ],
            'delete' => [
                'class' => DeleteBehavior::className(),
            ]
        ];
    }
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'vote';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['vote_id', 'vote_title', 'vote_numbers', 'start_date', 'end_date', 'bitcoin_address'], 'required'],
            [['vote_desc'], 'string'],
            [['vote_numbers', 'deleted'], 'integer'],
            [['start_date', 'end_date', 'deleted_at', 'created_at', 'updated_at'], 'safe'],
            [['vote_id'], 'string', 'max' => 3],
            [['vote_title', 'bitcoin_address'], 'string', 'max' => 255],
            [['deleted_by', 'created_by', 'updated_by'], 'string', 'max' => 32],
            [['vote_id'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'vote_id' => 'Vote ID',
            'vote_title' => 'Nama Voting',
            'vote_desc' => 'Deskripsi',
            'vote_numbers' => 'Jumlah',
            'start_date' => 'Tanggal Mulai',
            'end_date' => 'Tanggal Berakhir',
            'bitcoin_address' => 'Bitcoin Address',
            'deleted' => 'Deleted',
            'deleted_at' => 'Deleted At',
            'deleted_by' => 'Deleted By',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCandidates()
    {
        return $this->hasMany(Candidate::className(), ['vote_id' => 'vote_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTokens()
    {
        return $this->hasMany(Token::className(), ['vote_id' => 'vote_id']);
    }


}

frontend/models/Vote.php
<?php

namespace frontend\models;

use common\behaviors\BlameableBehavior;
use common\behaviors\DeleteBehavior;
use common\behaviors\TimestampBehavior;
use Yii;

/**
 * This is the model class for table "vote".
 *
 * @property string $vote_id
 * @property string $vote_title
 * @property string $vote_desc
 * @property int $vote_numbers
 * @property string $start_date
 * @property string $end_date
 * @property string $bitcoin_address
 * @property int $deleted
 * @property string $deleted_at
 * @property string $deleted_by
 * @property string $created_at
 * @property string $created_by
 * @property string $updated_at
 * @property string $updated_by
 *
 * @property Candidate[] $candidates
 * @property Token[] $tokens
 */
class Vote extends \yii\db\ActiveRecord
{
    /**
     * behaviour to add created_at and updatet_at field with current datetime (timestamp)
     * and created_by and updated_by field with current user id (blameable)
     */
    public function behaviors(){
        return [
            'timestamp' => [
                'class' => TimestampBehavior::className(),
            ],
            'blameable' => [
                'class' => BlameableBehavior::className(),
            ],
            'delete' => [
                'class' => DeleteBehavior::className(),
            ]
        ];
    }
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'vote';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['vote_id', 'vote_title', 'vote_numbers', 'start_date', 'end_date', 'bitcoin_address'], 'required'],
            [['vote_desc'], 'string'],
            [['vote_numbers', 'deleted'], 'integer'],
            [['start_date', 'end_date', 'deleted_at', 'created_at', 'updated_at'], 'safe'],
            [['vote_id'], 'string', 'max' => 3],
            [['vote_title', 'bitcoin_address'], 'string', 'max' => 255],
            [['deleted_by', 'created_by', 'updated_by'], 'string', 'max' => 32],
            [['vote_id'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'vote_id' => 'Vote ID',
            'vote_title' => 'Nama Voting',
            'vote_desc' => 'Deskripsi',
            'vote_numbers' => 'Jumlah',
            'start_date' => 'Tanggal Mulai',
            'end_date' => 'Tanggal Berakhir',
            'bitcoin_address' => 'Bitcoin Address',
            'deleted' => 'Deleted',
            'deleted_at' => 'Deleted At',
            'deleted_by' => 'Deleted By',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCandidates()
    {
        return $this->hasMany(Candidate::className(), ['vote_id' => 'vote_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTokens()
    {
        return $this->hasMany(Token::className(), ['vote_id' => 'vote_id']);
    }


}

backend/controllers/VoteController.php
<?php

namespace backend\controllers;


use backend\models\Model;
use backend\models\Candidate;
use backend\models\Voter;
use BitcoinPHP\BitcoinECDSA\BitcoinECDSA;
use Yii;
use backend\models\Vote;
use backend\models\search\VoteSearch;

use yii\base\DynamicModel;
use yii\bootstrap\ActiveForm;
use yii\db\Exception;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
/**
 * VoteController implements the CRUD actions for Vote model.
 */
class VoteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['index','view','vote-update','vote-add','download'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Vote models.
     * @return mixed
     */
    public function actionIndex()
    {
        if(Yii::$app->user->isGuest){
            return $this->redirect('site/login');
        }
        else{
            $searchModel = new VoteSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }
    }

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     * @throws \yii\base\InvalidConfigException
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $time =date("Y-m-d H:i:s");
        $today = date('Y-m-d H:i:s',strtotime('+7 hour',strtotime($time)));
        $start = Yii::$app->formatter->asDatetime($model->start_date,'php:Y-m-d H:i:s');
        $end = Yii::$app->formatter->asDatetime($model->end_date,'php:Y-m-d H:i:s');

        if($today<$start){
            \Yii::$app->getSession()->setFlash('warning', '<b>Perhatian!</b>&nbsp; Voting Belum dimulai.');
        }
        else if($today >= $start && $today <= $end){
            \Yii::$app->getSession()->setFlash('info', '<b>Info!</b>&nbsp; Voting sedang berlangsung.');
        }
        else{
            \Yii::$app->getSession()->setFlash('success', '<b>Info!</b>&nbsp; Voting Telah Berakhir.');
        }

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * @param $id
     * @return Response
     * @throws NotFoundHttpException
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
//    public function actionDelete($id)
//    {
//        $this->findModel($id)->delete();
//
//        return $this->redirect(['index']);
//    }

    /**
     * Finds the Vote model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Vote the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Vote::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }


    /**
     * @return array|string|Response
     * @throws NotFoundHttpException
     * @throws \PHPExcel_Exception
     * @throws \PHPExcel_Reader_Exception
     */
    public function actionVoteAdd(){
        $modelVote = new Vote;
        $modelsCandidate = [new Candidate];
        $modelVoter = new Voter();
        $modelImport = new DynamicModel([
            'fileImport'=>'File Import',
        ]);
        $modelImport->addRule(['fileImport'], 'required');
        $modelImport->addRule(['fileImport'], 'file', ['extensions' => 'ods,xls,xlsx'], ['maxSize' => 1024 * 1024]);

        if ($modelVote->load(Yii::$app->request->post())) {

            $modelVote->vote_id = $this->generateId();
            $modelVote->bitcoin_address = $this->generateAddress();
            $modelsCandidate = Model::createMultiple(Candidate::classname());
            Model::loadMultiple($modelsCandidate, Yii::$app->request->post());
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ArrayHelper::merge(
                    ActiveForm::validateMultiple($modelsCandidate),
                    ActiveForm::validate($modelVote)
                );
            }
            if ($modelVote->save(false)) {
                foreach ($modelsCandidate as $modelCandidate) {
                    $modelCandidate->vote_id = $modelVote->vote_id;
                    $flag = $modelCandidate->save(false);
                }
            }

            if ($flag) {
                $modelImport->fileImport = \yii\web\UploadedFile::getInstance($modelImport, 'fileImport');
                $modelVoteNew = $this->findModel($modelVote->vote_id);
                if($modelImport->fileImport && $modelImport->validate()){
                    $inputFileType = \PHPExcel_IOFactory::identify($modelImport->fileImport->tempName);
                    $objReader = \PHPExcel_IOFactory::createReader($inputFileType);
                    $objPHPExcel = $objReader->load($modelImport->fileImport->tempName);
                    $sheetData = $objPHPExcel->getActiveSheet()->toArray(null, true, true, true);
                    $baseRow = 2;
                    $errorEmail = array();
                    $temp_email = array();
                    while (!empty($sheetData[$baseRow]['A'])) {
                        /*Email Sementara */
                        $temp_email[$sheetData[$baseRow]['A']] = $sheetData[$baseRow]['B'];
                        $baseRow++;
                    }
                    /*Cek Duplicate*/
                    $result = array_unique($temp_email);
                    foreach ($result as $name => $email){
                        $modelVoter->subject = 'Voting '. $modelVote->vote_title;
                        $modelVoter->body = '<br> Hi ' . $name . ',<br> Berikut token anda untuk melakukan voting di <strong>' . $modelVote->vote_title . '</strong><br>
                      <h3>Token : <b>' . $modelVoter->generateToken(1, $modelVote->vote_id) . '</b></h3><br> Berikut Link untuk mengakses voting<br>  
                      <h2>
                        <a href="http://localhost/ChainVoting/frontend/web/voter/get-vote?id=' . $modelVote->vote_id . '">Klik disini</a>
                      </h2>';
                        if ($modelVoter->sendMail($email)) {
                            Yii::$app->session->setFlash('success', 'Pemilih berhasil didaftarkan.');
                        }
                        else{
                            $errorEmail[] = $email;
                        }
                    }
                    if(!empty($errorEmail)){
                        foreach ($errorEmail as $item){
                            Yii::$app->session->addFlash('error', 'Gagal Mengirim Email. Ke '.$item);
                        }
                    }

                    $modelVoteNew->vote_numbers = count($result);
                    if($modelVoteNew->save(false)){
                        return $this->redirect(['view', 'id' => $modelVote->vote_id]);
                    }
                }
            }
        }
        return $this->render('voteCreate', [
            'modelVote' => $modelVote,
            'modelsCandidate' => (empty($modelsCandidate)) ? [new Candidate] : $modelsCandidate,
            'modelImport'=>$modelImport,
        ]);
    }

    /**
     * @param $id
     * @return string|Response
     * @throws NotFoundHttpException
     */
    public function actionVoteUpdate($id){
        $modelVote = $this->findModel($id);
        $modelsCandidate = Candidate::find()->where(['vote_id'=>$id])->all();
        $time =date("Y-m-d H:i:s");
        $today = date('Y-m-d H:i:s',strtotime('+7 hour',strtotime($time)));

        if($today <= $modelVote->start_date) {
            if($modelVote->load(Yii::$app->request->post())){
                $oldIDs = ArrayHelper::map($modelsCandidate, 'candidate_id', 'candidate_id');
                $modelsCandidate = Model::createMultiple(Candidate::classname(), $modelsCandidate);
                Model::loadMultiple($modelsCandidate, Yii::$app->request->post());
                $deletedIDs = array_diff($oldIDs, array_filter(ArrayHelper::map($modelsCandidate, 'candidate_id', 'candidate_id')));
                if($modelVote->save(false)){
                    if(!empty($deletedIDs)){
                        Candidate::deleteAll(['candidate_id'=>$deletedIDs]);
                    }
                    foreach ($modelsCandidate as $modelCandidate){
                        $modelCandidate->vote_id = $modelVote->vote_id;
                        $flag = $modelCandidate->save(false);
                    }
                }
                if ($flag) {
                    return $this->redirect(['view', 'id' => $modelVote->vote_id]);
                }
            }
            return $this->render('VoteUpdate', [
                'modelVote' => $modelVote,
                'modelsCandidate' => (empty($modelsCandidate)) ? [new Candidate] : $modelsCandidate,
            ]);
        } else{
            Yii::$app->session->addFlash('error', 'Voting tidak dapat diperbarui karena voting sedang berlangsung');

backend/views/vote/VoteImport.php
<?php

/**
 * Created by PhpStorm.
 * User: MarchelHutagalung
 * Date: 3/25/2019
 * Time: 4:32 PM
 */

/* @var $this \yii\web\View */
/* @var $modelImport \yii\base\DynamicModel */
/* @var $model \backend\models\Voter */

use backend\models\Vote;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

$this->title = 'Tambah Pemilih';
$this->params['breadcrumbs'][] = ['label' => 'Votes', 'url' => ['create']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="voter-form">

    <?php $form = ActiveForm::begin(['options'=>['enctype'=>'multipart/form-data']]);?>

    <?php
    $vote = Vote::find()->all();
    $listVote = ArrayHelper::map($vote,'vote_id','vote_title');
    ?>
    <?= $form->field($modelVoter, 'vote_id')->dropDownList($listVote)->label("Voting");?>
    <?= $form->field($modelImport,'fileImport')->fileInput() ?>

    <div class="form-group">
        <?= Html::submitButton('<span class="fa fa-upload"></span>&nbsp;Import',['class'=>'btn btn-success']);?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

backend/views/vote/VoteUpdate.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Vote */

$this->title = 'Tambah Vote';
$this->params['breadcrumbs'][] = ['label' => 'Votes', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="vote-create">

    <?= $this->render('_voteUpdate', [
        'modelVote'=> $modelVote,
        'modelsCandidate'=>$modelsCandidate,
    ]) ?>

</div>

backend/views/vote/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\search\VoteSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="vote-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'vote_title', [
        'inputOptions' => ['autofocus' => 'autofocus', 'class' => 'form-control transparent']
    ])->textInput()->input('text', ['placeholder' => "Nama Voting"])->label(false);?>
    <div class="form-group">
        <?= Html::submitButton('Cari', ['class' => 'btn btn-primary btn-md']) ?>
        <?= Html::a('Hapus', ['index'], ['class' => 'btn btn-default btn-md']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/vote/_voteCreate.php
<?php

/**
 * Created by PhpStorm.
 * User: MarchelHutagalung
 * Date: 4/25/2019
 * Time: 9:18 PM
 */

/* @var $this \yii\web\View */
/* @var $model \backend\models\Vote|\yii\db\ActiveRecord */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use wbraganca\dynamicform\DynamicFormWidget;
use kartik\datetime\DateTimePicker;
$datetime = new DateTime();
$js = '
jQuery(".dynamicform_wrapper").on("afterInsert", function(e, item) {
    jQuery(".dynamicform_wrapper .panel-title-address").each(function(index) {
        jQuery(this).html("Kandidat : " + (index + 1))
    });
});

jQuery(".dynamicform_wrapper").on("afterDelete", function(e) {
    jQuery(".dynamicform_wrapper .panel-title-address").each(function(index) {
        jQuery(this).html("Kandidat: " + (index + 1))
    });
});

jQuery("#add-vote").click(function(){
    jQuery("#contentPege").showLoading();
});
';
use nirvana\showloading\ShowLoadingAsset;
ShowLoadingAsset::register($this);
$this->registerJs($js);
?>
<div class="vote-form">

    <?php $form = ActiveForm::begin(['id' => 'dynamic-form']); ?>
            <?= $form->field($modelVote, 'vote_title')->textInput(['maxlength' => true]) ?>
            <?= $form->field($modelVote, 'vote_desc')->widget(\yii\redactor\widgets\Redactor::className()) ?>
    <div class="row">
        <div class="col-sm-6">
                <?= $form->field($modelVote, 'start_date')->widget(DateTimePicker::className(),[
                    'pluginOptions' => [
                            'format'=>'yyyy-mm-dd hh:ii:00',
                            'startDate' => date($datetime->format("Y-m-d")),
                            'todayHighlight' => true,
                            'autoclose'=>true,
                    ]
                ]) ?>
        </div>

        <div class="col-sm-6">
                <?= $form->field($modelVote, 'end_date')->widget(DateTimePicker::className(),[
                    'pluginOptions' => [
                        'format'=>'yyyy-mm-dd hh:ii:00',
                        'startDate' => date($datetime->format("Y-m-d")),
                        'todayHighlight' => true,
                        'autoclose'=>true,
                    ]
                ]) ?>
        </div>
    </div>
    <?php if (!$modelVote->isNewRecord) { ?>
            <?php echo $form->field($modelVote, 'vote_numbers')->textInput(['disabled'=>true])->label('Jumlah Pemilih')?>
    <?php } ?>
    <?php DynamicFormWidget::begin([
        'widgetContainer' => 'dynamicform_wrapper', // required: only alphanumeric characters plus "_" [A-Za-z0-9_]
        'widgetBody' => '.container-items', // required: css class selector
        'widgetItem' => '.item', // required: css class
        'limit' => 10, // the maximum times, an element can be cloned (default 999)
        'min' => 1, // 0 or 1 (default 1)
        'insertButton' => '.add-item', // css class
        'deleteButton' => '.remove-item', // css class
        'model' => $modelsCandidate[0],
        'formId' => 'dynamic-form',
        'formFields' => [
            'candidate_name',
            'candidate_desc',
        ],
    ]); ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <i class="fa fa-user"></i> Kandidat
            <button type="button" class="pull-right add-item btn btn-success btn-xs"><i class="fa fa-plus"></i> Tambah Kandidat</button>
            <div class="clearfix"></div>
        </div>
        <div class="panel-body container-items"><!-- widgetContainer -->
            <?php foreach ($modelsCandidate as $index => $modelCandidate): ?>
                <div class="item panel panel-default"><!-- widgetBody -->
                    <div class="panel-heading">
                        <span class="panel-title-address">Kandidat ke : <?= ($index + 1) ?></span>
                        <button type="button" class="pull-right remove-item btn btn-danger btn-xs"><i class="fa fa-minus"></i></button>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <?php
                        // necessary for update action.
                        if (!$modelCandidate->isNewRecord) {
                            echo Html::activeHiddenInput($modelCandidate, "[{$index}]candidate_id");
                        }
                        ?>
                        <?= $form->field($modelCandidate, "[{$index}]candidate_name")->textInput(['maxlength' => true]) ?>
                        <?= $form->field($modelCandidate, "[{$index}]candidate_desc")->textInput(['maxlength' => true]) ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <?php DynamicFormWidget::end(); ?>
    <?php if ($modelCandidate->isNewRecord) { ?>
        <?= $form->field($modelImport,'fileImport')->fileInput()->label('File Pemilih') ?>
        <?= Html::a('Download Template', ['download'], ['class' => 'btn btn-success']) ?>
        <p class="help-block">Silahkan masukkan file excel daftar pemilih.</p>
    <?php } ?>
    <div class="form-group">
        <?= Html::submitButton($modelCandidate->isNewRecord ? 'Tambah' : 'Perbarui', ['class' => 'btn btn-primary','id'=>'add-vote']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/vote/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;


/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\VoteSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Voting';
$this->params['breadcrumbs'][] = $this->title;
$uiHelper=\Yii::$app->uiHelper;
?>
<div class="vote-index">
    <?=$uiHelper->beginContentRow() ?>

    <?=$uiHelper->beginContentBlock(['id' => 'grid-system2',
        'width' => 12,
        'type' => 'success'
    ]); ?>
    <?php  echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?php // Html::a('Create Vote', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'tableOptions' => ['class'=>'table table-hover'],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
//            'vote_id',
            [
                    'attribute' => 'vote_title',
                    'value' => 'vote_title',
            ],
            [
                'attribute' => 'vote_desc',
                'format' => 'raw',
            ],
            [
                'format' => 'raw',
                'label' => 'Status',
                'headerOptions' => ['style' => 'color:#3c8dbc'],
                'value'=>function($model){
                    $time =date("Y-m-d H:i:s");
                    $today = date('Y-m-d H:i:s',strtotime('+7 hour',strtotime($time)));

                    $start = Yii::$app->formatter->asDatetime($model->start_date,'php:Y-m-d H:i:s');
                    $end = Yii::$app->formatter->asDatetime($model->end_date,'php:Y-m-d H:i:s');

                    if($today<$start){
                        return '<span class="label label-warning">Menunggu</span>';
                    }
                    else if($today >= $start && $today <= $end){
                        return '<span class="label label-primary">Sedang Mulai</span>';
                    }
                    else{
                        return '<span class="label label-success">Selesai</span>';
                    }
                }
            ],
            ['class' => 'yii\grid\ActionColumn',
                'template'=>'{view}{result}',
                'buttons'=>[
                    'view' => function ($url,$model) {
                        $url = Url::to(['vote/view', 'id' => $model->vote_id]);
                        return Html::a('Rincian', $url,['class'=>'btn btn-sm btn-primary','style'=>'margin-right : 5px;']);
                    },
                    'result'=> function($url,$model){
                        $time =date("Y-m-d H:i:s");
                        $today = date('Y-m-d H:i:s',strtotime('+7 hour',strtotime($time)));
                        $start = Yii::$app->formatter->asDatetime($model->start_date,'php:Y-m-d H:i:s');
                        $end = Yii::$app->formatter->asDatetime($model->end_date,'php:Y-m-d H:i:s');
                        $url = Yii::$app->urlManagerFrontEnd->createAbsoluteUrl('/voter/result?id=').$model->vote_id;
                        if($today<$start){
                            return '';
                        }
                        else if($today >= $start && $today <= $end){
                            return Html::a('Hasil Sementara', $url,['class'=>'btn btn-sm btn-success','target'=>'_blank']);
                        }
                        else{
                            return Html::a('Hasil', $url,['class'=>'btn btn-sm btn-success','target'=>'_blank']);
                        }
                    }
                ]
            ],
        ],
    ]);
    ?>
    <?= $uiHelper->endContentBlock()?>

    <?=$uiHelper->endContentRow() ?>
</div>

backend/views/vote/voteCreate.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Vote */

$this->title = 'Tambah Vote';
$this->params['breadcrumbs'][] = ['label' => 'Votes', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
$uiHelper=\Yii::$app->uiHelper;
?>
<div class="vote-create">
    <?=$uiHelper->beginContentRow() ?>

    <?=$uiHelper->beginContentBlock(['id' => 'grid-system2',
        'width' => 12,
        'type' => 'success'
    ]); ?>
    <?= $this->render('_voteCreate', [
        'modelVote'=> $modelVote,
        'modelsCandidate'=>$modelsCandidate,
        'modelImport'=>$modelImport,
    ]) ?>
    <?= $uiHelper->endContentBlock()?>
    <?=$uiHelper->endContentRow() ?>
</div>