backend/models/Voter.php
<?php

namespace backend\models;

use BitcoinPHP\BitcoinECDSA\BitcoinECDSA;
use Yii;
use yii\base\Model;

/**
 * Voter is the model behind the voter
 */

class Voter extends Model
{
    public $name;
    public $email;
    public $subject;
    public $body;
    public $vote_id;

    /**
     * {@inheritdoc}
     */
     public function rules(){
         return [
             [['name','email','vote_id'],'required'],
             [['subject','body','vote_id'],'string'],
             ['email','email'],
         ];
     }


     /**
     * {@inheritdoc}
     */
     public function attributeLabels(){
         return [
             'verifyCode'=>'Verification Code',
             'name'=>'Nama Pemilih',
         ];
     }

     public function sendMail($email){
        return Yii::$app->mailer->compose()
            ->setTo($email)
            ->setFrom([Yii::$app->params['adminEmail'] => 'Admin Voting'])
            ->setSubject($this->subject)
            ->setHtmlBody($this->body)
            ->send();
     }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVote()
    {
        return $this->hasOne(Vote::className(), ['vote_id' => 'vote_id']);
    }

    public function generateToken($n, $vote_id)
    {
        $model = new Token();
        $number = intval($n);
        $bitcoin = new BitcoinECDSA();
        $bitcoin->setNetworkPrefix('6f');
        if ($n > 0 && $number < 1000) {
            for ($i = 0; $i < $n; $i++) {
                $token = $model->randomToken();
                $model->token = $token;
                $model->vote_id = $vote_id;
                $bitcoin->generateRandomPrivateKey();
                $model->bitcoin_pubkey = $bitcoin->getPubKey();
                $model->bitcoin_pvkey = $bitcoin->getWif();
                $model->bitcoin_address = $bitcoin->getAddress();
                if ($model->save(false)) {
                    return $model->token;
                }
            }
        }
        return false;
    }
}
?>

frontend/controllers/VoterController.php
<?php
/**
 * Created by PhpStorm.
 * User: MarchelHutagalung
 * Date: 3/22/2019
 * Time: 2:10 PM
 */

namespace frontend\controllers;


use frontend\models\search\CandidateSearch;
use frontend\models\search\VoteSearch;
use frontend\models\Token;
use frontend\models\User;
use frontend\models\Vote;
use Yii;
use yii\web\Controller;

class VoterController extends Controller
{
    public function actionIndex(){
        $searchModel = new VoteSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index',[
            'dataProvider'=>$dataProvider
        ]);
    }

    public function actionGetVote($id){
        $cek = Vote::find()->where(['vote_id'=>$id])->one();
        if(is_object($cek)){
            $time =date("Y-m-d H:i:s");
            $today = date('Y-m-d H:i:s',strtotime('+7 hour',strtotime($time)));
            $start = Yii::$app->formatter->asDatetime($cek->start_date,'php:Y-m-d H:i:s');
            $end = Yii::$app->formatter->asDatetime($cek->end_date,'php:Y-m-d H:i:s');
            if($today<$start){
                return $this->render('wait',['message'=>'Voting Belum dimulai']);
            }
            else if($today >= $start && $today <= $end){
                $vote_address = $cek->bitcoin_address;
                $searchModel = new CandidateSearch();
                $dataProvider = $searchModel->searchById(Yii::$app->request->queryParams,$id);
                $model = new Token();
                if($model->load(Yii::$app->request->post()) && $model->validate()) {
                    $status = Token::find()->where(['token' => $model->token])->one();

                    if(is_object($status)){
                        $tokenId = $status->token;
                        if ($status->is_used != 0 || $status->is_paid == 0) {
                            Yii::$app->session->setFlash('error', 'Maaf, Token anda telah digunakan atau belum diizinkan untuk voting');
                            return $this->render('insert',[
                                'model'=>$model,
                            ]);
                        } else {
                            return $this->render('ballot', [
                                'dataProvider' => $dataProvider,
                                'tokenId' => $tokenId,
                                'vote_address'=>$vote_address,
                            ]);
                        }
                    }
                    else{
                        Yii::$app->session->setFlash('error', 'Maaf, Token anda tidak valid.');
                        return $this->render('insert',[
                            'model'=>$model,
                        ]);
                    }
                }
                else{
                    return $this->render('insert',[
                        'model'=>$model,
                    ]);
                }
            }
            else{
                return $this->render('wait',['message'=>'Voting Telah Selesai']);
            }

        }
        else{
            return $this->redirect('error');
        }
    }

    public function actionResult($id){
        $model = Vote::find()->where(['vote_id'=>$id])->one();
        if(is_object($model)){
        return $this->render('result',
            [
                'model' => $model,
            ]);
        }
        else{
            return $this->redirect(['site/error']);
        }
    }

    public function actionError(){
        return $this->render('error');
    }
}

frontend/views/voter/ballot.php
<?php

/**
 * Created by PhpStorm.
 * User: MarchelHutagalung
 * Date: 3/21/2019
 * Time: 9:00 AM
 */
use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use frontend\assets\Chartist;

Chartist::register($this);
/* @var $this \yii\web\View */
/* @var $dataProvider \yii\data\ActiveDataProvider */

use frontend\assets\VoteAsset;
$this->title = 'Voting';
$this->params['breadcrumbs'][] = $this->title;

VoteAsset::register($this);
?>
<div class="vote-index">

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'tableOptions' => ['class'=>'table table-striped table-hover'],
        'columns' => [
            [
                'attribute' => 'candidate_id',
                'format' => 'raw',
                'label'=>'',
                'value'=> function($model){
                    return Html::img('@web/images/user.png',['style'=>'height:30px; max-width:100%']);
                },
                'contentOptions' => ['style' => 'width:80px; text-align: center;'],
                'headerOptions' => ['style' => 'text-align: center;'],
            ],
            [
                'attribute' => 'candidate_name',
                'format'=>'raw',
                'label'=>'Nama',
                'contentOptions' => ['style' => 'width:80px; text-align: center;'],
                'headerOptions' => ['style' => 'text-align: center;'],
            ],

            [
                'attribute' => 'candidate_desc',
                'format' => 'raw',
                'label' => 'Deskripsi',
            ],
            [
                'class'=>'yii\grid\ActionColumn',
                'header' => 'Aksi',
                'headerOptions' => ['style'=>'color:#3c8dbc'],
                'template' => '{voting}',
                'buttons' => [
                        'voting'=>function($url,$model){
                            $url = Url::to(['voter/voting','id'=>$model->candidate_id]);
                            //return Html::a('Vote',$url,['class'=>'btn btn-primary']);|
                            return Html::button('VOTE <span class="glyphicon glyphicon-pushpin"></span>',['value'=>$model->candidate_id,'class'=>'btn btn-sm btn-primary voteBtn']);
                        }
                ]

            ]
        ],
    ])
    ?>
     <input type="hidden" id="tokenId" value="<?=$tokenId;?>">
    <input type="hidden" class="voteId" value="<?=$_GET['id'];?>">
    <input type="hidden" id="vote_address" value="<?=$vote_address?>">
</div>

frontend/views/voter/error.php
<?php

/**
 * Created by PhpStorm.
 * User: MarchelHutagalung
 * Date: 3/22/2019
 * Time: 3:10 PM
 */

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */
$name = 'Not Found (#404)';
$this->title = $name;
?>
<section class="content">
    <div class="error-page">
        <div class="error-content">
            <h1><?= $name ?></h1>

            <h5 class="alert alert-danger">
                Voting tidak ditemukan silahkan cek email anda untuk mendapatkan <b>url </b> yang valid
            </h5>
            <a href='<?= Yii::$app->homeUrl ?>' class="btn btn-primary">Kembali ke Halaman utama</a>
        </div>
    </div>

</section>

frontend/views/voter/index.php
<?php

/**
 * Created by PhpStorm.
 * User: MarchelHutagalung
 * Date: 3/22/2019
 * Time: 3:20 PM
 */

/* @var $this \yii\web\View */
/* @var $dataProvider \yii\data\ActiveDataProvider */

use aneeshikmat\yii2\Yii2TimerCountDown\Yii2TimerCountDown;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

$this->title = 'Daftar Voting';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="vote-index">
    <p>
        <?php // Html::a('Create Vote', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'tableOptions' => ['class' => 'table table-hover'],
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
//            'vote_id',
            [
                'attribute' => 'vote_title',
                'value' => 'vote_title',
                'label' => 'Judul',
            ],
            [
                'attribute' => 'vote_desc',
                'format' => 'raw',
                'label' => 'Deskripsi',
            ],
            [
                'format' => 'raw',
                'label' => 'Status',
                'headerOptions' => ['style' => 'color:#3c8dbc'],
                'value'=>function($model){
                    $time =date("Y-m-d H:i:s");
                    $today = date('Y-m-d H:i:s',strtotime('+7 hour',strtotime($time)));
                    $start = Yii::$app->formatter->asDatetime($model->start_date,'php:Y-m-d H:i:s');
                    $end = Yii::$app->formatter->asDatetime($model->end_date,'php:Y-m-d H:i:s');

                    if($today<$start){
                        return '<span class="label label-warning">Menunggu</span>';
                    }
                    else if($today >= $start && $today <= $end){
                        return '<span class="label label-primary">Sedang Mulai</span>';
                    }
                    else{
                        return '<span class="label label-success">Selesai</span>';
                    }
                }
            ],
//            [
//                'attribute' => 'end_date',
//                'label'=>'Timer',
//                'format'=>'raw',
//                'value'=>function($model){
//$callBackScript = <<<JS
//        document.getElementById('time-down-counter').className += "label label-danger";
//JS;
//                    $date = date('Y-m-d H:i:s',strtotime('-7 hour',strtotime($model->end_date)));
//                    return '
//                            <div id="time-down-counter" class=""></div>'.Yii2TimerCountDown::widget([
//                            'countDownIdSelector' => 'time-down-counter',
//                            'countDownDate' => strtotime($date) * 1000,
////                            'countDownDate' => strtotime("+1 minute") * 1000,
//                            'countDownResSperator' => ':',
//                            'countDownOver' => '00:00:00',
//                            'countDownReturnData' => 'from-days',
//                            'templateStyle' => 0,
//                            'callBack' => $callBackScript
//                        ]);
//                }
//            ],
            [
                'class'=>'yii\grid\ActionColumn',
                'header'=>'Aksi',
                'headerOptions' => ['style'=>'color:#3c8dbc'],
                'template' => '{hasil}{vote}',
                'buttons' =>
                [
                    'hasil'=>function($url,$model){
                        $url = Url::to(['voter/result','id'=>$model->vote_id]);
                        $time =date("Y-m-d H:i:s");
                        $today = date('Y-m-d H:i:s',strtotime('+7 hour',strtotime($time)));
                        $start = Yii::$app->formatter->asDatetime($model->start_date,'php:Y-m-d H:i:s');
                        $end = Yii::$app->formatter->asDatetime($model->end_date,'php:Y-m-d H:i:s');

                        if($today<$start){
                            return '';
                        }
                        else if($today >= $start && $today <= $end){
                            return Html::a('<span class="glyphicon glyphicon-search"></span> Hasil',$url,['class'=>'label label-primary','style'=>'margin-right : 10px;']);
                        }
                        else{
                            return Html::a('<span class="glyphicon glyphicon-search"></span> Hasil',$url,['class'=>'label label-primary']);
                        }

                    },
                    'vote'=>function($url,$model){
                        $url = Url::to(['voter/get-vote','id'=>$model->vote_id]);
                        $time =date("Y-m-d H:i:s");
                        $today = date('Y-m-d H:i:s',strtotime('+7 hour',strtotime($time)));
                        $start = Yii::$app->formatter->asDatetime($model->start_date,'php:Y-m-d H:i:s');
                        $end = Yii::$app->formatter->asDatetime($model->end_date,'php:Y-m-d H:i:s');

                        if($today<$start){
                            return '';
                        }
                        else if($today >= $start && $today <= $end){
                            return Html::a('<span class="glyphicon glyphicon-pushpin"></span> Vote',$url,['class'=>'label label-success']);
                        }
                        else{
                            return '';
                        }
                    }
                ]
            ]
        ],
    ]);
    ?>
</div>

frontend/views/voter/insert.php
<?php

/**
 * Created by PhpStorm.
 * User: MarchelHutagalung
 * Date: 3/25/2019
 * Time: 9:40 AM
 */

/* @var $this \yii\web\View */
/* @var $model \backend\models\Token */
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;
$this->title = 'Token';
?>

<div class="token-form">
    <?php
    $form = ActiveForm::begin([
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n{beginWrapper}\n{input}\n{error}\n{endWrapper}\n{hint}",
            'horizontalCssClasses' => [
                'label' => 'col-sm-2',
                'wrapper' => 'col-sm-8',
                'error' => '',
                'hint' => '',
            ],
        ],
        //'enableAjaxValidation'=>true,
    ]) ?>
    <center>
        <h4>MASUKKAN TOKEN ANDA</h4>
    </center>
    <?= $form->field($model,'token')->textInput(['autofocus'=>true])->label('')?>
    <div class="form-group">
        <div class="col-sm-8 col-md-offset-2">
            <?= Html::submitButton('ENTER', ['class' => 'btn btn-primary form-control', 'name' => 'contact-button']) ?>
        </div>
    </div>
    <style>
        .form-group{
            margin-bottom: 0px;
        }
        .token-form{
            padding-top: 200px;
        }
    </style>

    <?php ActiveForm::end();?>
</div>

frontend/views/voter/result.php
<?php

/**
 * Created by PhpStorm.
 * User: MarchelHutagalung
 * Date: 4/3/2019
 * Time: 3:50 PM
 */

use aneeshikmat\yii2\Yii2TimerCountDown\Yii2TimerCountDown;
use frontend\assets\TallyAsset;
use yii\bootstrap\Html;

/* @var $this \yii\web\View */
$this->title = 'Perhitungan';
TallyAsset::register($this);
?>

<div class="row">
    <div class="col-md-12">
        <div class="jumbotron">
            <div class="panel panel-headline">
                <input type="hidden" class="vote_id" value="<?=$_GET['id']?>">
                <input type="hidden" class="admaddress" value="<?=$model->bitcoin_address;?>">
                <input type="hidden" class="vtnumbers" value="<?=$model->vote_numbers;?>">
                <div class="panel-heading">
                    <h2 class="panel-title"> <b>PENGHITUNGAN </b></h2>
                    <p class="panel-subtitle"><strong></strong><span class="tally-status" id="tallys"></span></p>
                    <span class="percentage"></span>
                </div>
                <?php
                $date = date('Y-m-d H:i:s',strtotime('-7 hour',strtotime($model->end_date)));
                $callBackScript = <<<JS
            document.getElementById('time-down-counter').className += "label label-danger";
JS;
                ?>

                <div id="time-down-counter"></div>
                <?= Yii2TimerCountDown::widget([
                    'countDownIdSelector' => 'time-down-counter',
                    'countDownDate' => strtotime($date) * 1000,
                    'countDownResSperator' => ':',
                    'addSpanForResult' => false,
                    'addSpanForEachNum' => false,
                    'countDownOver' => 'Selesai',
                    'countDownReturnData' => 'from-days',
                    'templateStyle' => 2,
                    'getTemplateResult' => 0,
                    'callBack' => $callBackScript
                ]) ?>
        </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="ct-chart ct-perfect-fourth"></div>
                    </div>
                    <div class="col-md-6">
                        <div class="ct-bar-chart ct-perfect-fourth"></div>
                    </div>
                </div>
                <hr>
                <br>
                <div class="row">
                    <div class="col-md-12">
                        <input type="hidden" class="vote-candidate" value="" />
                        <div class="list-candidate">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

frontend/views/voter/wait.php
<?php

/**
 * Created by PhpStorm.
 * User: MarchelHutagalung
 * Date: 3/22/2019
 * Time: 3:10 PM
 */

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */
$name = 'Not Found (#404)';
$this->title = $name;
?>
<section class="content">
    <div class="error-page">
        <div class="error-content">
            <h1><?= $name ?></h1>

            <h5 class="alert alert-danger">
                <?=$message?>
            </h5>
            <a href='<?= Yii::$app->homeUrl ?>' class="btn btn-primary">Kembali ke Halaman utama</a>
        </div>
    </div>

</section>